apiVersion: v1
kind: Service
metadata:
  name: cldb-svc
  namespace: mapr-cluster
  labels:
    env: mapr-cluster-node
spec:
  ports:
  - name: server
    port: 7222
  - name: web
    port: 7221
  - name: jmx
    port: 7220
  - name: mfs1
    port: 5660
  - name: mfs2
    port: 5692
  - name: mfs3
    port: 5724
  - name: mfs4
    port: 5756
  clusterIP: None
  selector:
    role: cldb
