# Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved
kind: Pod
apiVersion: v1
metadata:
  name: sysbench-provisioner
  namespace: sysbench-tests
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"
    volumeMounts:
      - name: sysbench-pvc
        mountPath: "/sysbenchvolume"
  restartPolicy: "Never"
  volumes:
    - name: sysbench-pvc
      persistentVolumeClaim:
        claimName: sysbench-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sysbench-pvc
  namespace: sysbench-tests
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sysbench-storage
  resources:
    requests:
      storage: 500G
