# Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved
apiVersion: v1
kind: Pod
metadata:
  name: test-simple
  namespace: mapr-examples
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - data
  containers:
  - name: sysbench
    image: dotnetdr/sysbench:0.5
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - mountPath: /vol1
      name: maprflex
    resources:
      requests:
        memory: "5Gi"
        cpu: "8"
  volumes:
    - name: maprflex
      flexVolume:
        driver: "mapr.com/maprfs"
        options:
          volumePath: "/vol1"
          cluster: "archerx"
          platinum: "true"
          cldbHosts: "10.47.0.2 10.41.128.2"
          securityType: "unsecure"
